IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'Accolite_Bank')
BEGIN
  CREATE DATABASE Accolite_Bank
END
GO

USE Accolite_Bank
GO

IF OBJECT_ID(N'dbo.Users', N'U') IS NULL
BEGIN
	CREATE TABLE dbo.Users (
		Id INT IDENTITY (1, 1) NOT NULL
			CONSTRAINT PK_UserId PRIMARY KEY CLUSTERED,
		FirstName NVARCHAR(64) NULL,
		LastName NVARCHAR(64) NULL,
		Phone NVARCHAR(16) NULL,
		Email NVARCHAR(64) NOT NULL,
		Created DATETIME NOT NULL,
		Updated DATETIME NOT NULL
	)
END

IF OBJECT_ID(N'dbo.Accounts', N'U') IS NULL
BEGIN
	CREATE TABLE dbo.Accounts (
		Id INT IDENTITY (1, 1) NOT NULL
			CONSTRAINT PK_AccountId PRIMARY KEY CLUSTERED,
        Name NVARCHAR(16) NOT NULL,
		UserId INT NOT NULL
			CONSTRAINT FK_Account_User FOREIGN KEY REFERENCES Users(Id),
        Amount DECIMAL(19,4) NOT NULL,
		Created DATETIME NOT NULL,
		Updated DATETIME NOT NULL
	)
END
